// <auto-generated />
using System;
using BD_Wholesale_warehouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BD_Wholesale_warehouse.Migrations
{
    [DbContext(typeof(BD_Wholesale_warehouseContext))]
    [Migration("20201211083340_4")]
    partial class _4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Customers", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone_number")
                        .HasColumnType("int");

                    b.Property<long>("ProductID1")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductID2")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductID3")
                        .HasColumnType("bigint");

                    b.Property<long?>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Positions", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Demands")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duties")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job_title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PositionID")
                        .HasColumnType("bigint");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<long?>("StaffID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("StaffID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Product", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CustomersID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomersID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("CustomersID2")
                        .HasColumnType("bigint");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Packaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Product_ID")
                        .HasColumnType("bigint");

                    b.Property<long>("Product_typeID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Shelf_life")
                        .HasColumnType("datetime2");

                    b.Property<string>("Storage_conditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SuppliersID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SuppliersID1")
                        .HasColumnType("bigint");

                    b.Property<long?>("SuppliersID2")
                        .HasColumnType("bigint");

                    b.Property<long?>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CustomersID");

                    b.HasIndex("CustomersID1");

                    b.HasIndex("CustomersID2");

                    b.HasIndex("SuppliersID");

                    b.HasIndex("SuppliersID1");

                    b.HasIndex("SuppliersID2");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Product_type", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<long>("Product_type_ID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("Product_type");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Staff", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passport_data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PositionID")
                        .HasColumnType("bigint");

                    b.Property<long>("Staff_ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Suppliers", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Addres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone_number")
                        .HasColumnType("int");

                    b.Property<long>("ProductID1")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductID2")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductID3")
                        .HasColumnType("bigint");

                    b.Property<long>("SupplierID")
                        .HasColumnType("bigint");

                    b.Property<long?>("WarehouseID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Warehouse", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CustomerID")
                        .HasColumnType("bigint");

                    b.Property<string>("Delivery_method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Departure_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Order_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<long>("ProductID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Receipt_date")
                        .HasColumnType("datetime2");

                    b.Property<long>("StaffID")
                        .HasColumnType("bigint");

                    b.Property<long>("SupplierID")
                        .HasColumnType("bigint");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Customers", b =>
                {
                    b.HasOne("BD_Wholesale_warehouse.Models.Warehouse", null)
                        .WithMany("Customer_ID")
                        .HasForeignKey("WarehouseID");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Positions", b =>
                {
                    b.HasOne("BD_Wholesale_warehouse.Models.Staff", null)
                        .WithMany("Position_ID")
                        .HasForeignKey("StaffID");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Product", b =>
                {
                    b.HasOne("BD_Wholesale_warehouse.Models.Customers", null)
                        .WithMany("Product_ID1")
                        .HasForeignKey("CustomersID");

                    b.HasOne("BD_Wholesale_warehouse.Models.Customers", null)
                        .WithMany("Product_ID2")
                        .HasForeignKey("CustomersID1");

                    b.HasOne("BD_Wholesale_warehouse.Models.Customers", null)
                        .WithMany("Product_ID3")
                        .HasForeignKey("CustomersID2");

                    b.HasOne("BD_Wholesale_warehouse.Models.Suppliers", null)
                        .WithMany("Product_ID1")
                        .HasForeignKey("SuppliersID");

                    b.HasOne("BD_Wholesale_warehouse.Models.Suppliers", null)
                        .WithMany("Product_ID2")
                        .HasForeignKey("SuppliersID1");

                    b.HasOne("BD_Wholesale_warehouse.Models.Suppliers", null)
                        .WithMany("Product_ID3")
                        .HasForeignKey("SuppliersID2");

                    b.HasOne("BD_Wholesale_warehouse.Models.Warehouse", null)
                        .WithMany("Product_ID")
                        .HasForeignKey("WarehouseID");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Product_type", b =>
                {
                    b.HasOne("BD_Wholesale_warehouse.Models.Product", null)
                        .WithMany("Product_type_ID")
                        .HasForeignKey("ProductID");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Staff", b =>
                {
                    b.HasOne("BD_Wholesale_warehouse.Models.Warehouse", null)
                        .WithMany("Staff_ID")
                        .HasForeignKey("WarehouseID");
                });

            modelBuilder.Entity("BD_Wholesale_warehouse.Models.Suppliers", b =>
                {
                    b.HasOne("BD_Wholesale_warehouse.Models.Warehouse", null)
                        .WithMany("Supplier_ID")
                        .HasForeignKey("WarehouseID");
                });
#pragma warning restore 612, 618
        }
    }
}
